blank_issues_enabled: false
contact_links:
  - name: starlight-polyglot Documentation
    url: https://starlight-polyglot.vercel.app/
    about: Check the documentation for usage guides and API reference.
  - name: Starlight Documentation
    url: https://starlight.astro.build/
    about: General Starlight documentation and guides.
